dataset:
  name: swat
  raw_dir: datasets/raw
  normal_file: SWaT_Dataset_Normal_v1.csv
  attack_file: SWaT_Dataset_Attack_v0.csv

output:
  processed_dir: datasets/processed
  tensor_dir: datasets/tensors  

# Data preprocessing setup
window_shape : 150
train_stride : 10
test_stride : 150

# Framework setup
batch_size : 256
latent_dim : 20
epochs : 100
learning_rate : 0.0005


# Anomaly detection setup
percentile : 99
minimum_abnormal_features : 30
